# jenkinsci/jenkins/kustomization.yaml
namespace: jenkins

resources:
  - namespace.yaml

helmCharts:
  - name: jenkins
    repo: https://charts.jenkins.io
    version: 5.8.6
    releaseName: jenkins
    namespace: jenkins
    valuesFile: values.yaml
