controller:
  runAsUser: 1000
  fsGroup: 1000
  image:
    repository: jenkins/jenkins
    tag: 2.466.1-jdk21
    pullPolicy: "Always"
  admin:
    username: admin
    password: admin1234
  serviceType: LoadBalancer
  servicePort: 80
  ingress:
    enabled: false
  serviceAccount:
    create: false
    name: jenkins
  persistence:
    enabled: true
    storageClass: common-nfs
    size: 8Gi
  installPlugins: false
  additionalPlugins: []
agent:
  enabled: true
  kubernetes:
    namespace: jenkins
    defaultPodTemplate:
      label: jenkins-agent
      containers:
        - name: jnlp
          image: jenkins/inbound-agent:latest
      # 필요 시 리소스 설정
      defaultContainer: jnlp
