prometheus:
  enabled: false


extraArgs:
  - --feature-gates=ExperimentalGatewayAPISupport=true
  - --leader-election-namespace=cert-manager

cainjector:
  extraArgs:
    - --leader-election-namespace=cert-manager
