apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: minseoky-gateway
  namespace: istio
spec:
  gatewayClassName: istio  # 혹은 nginx 등 사용 중인 GatewayClass 이름
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: jenkins.minseoky.me
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            name: jenkins-cert
            group: ""
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 80
      hostname: jenkins.minseoky.me
      allowedRoutes:
        namespaces:
          from: All
