apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: minseoky-gateway
  namespace: istio-system
spec:
  gatewayClassName: istio  # 혹은 nginx 등 사용 중인 GatewayClass 이름
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - kind: Secret
            group: ''
            name: wildcard-minseoky-me
            namespace: cert-manager
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
