apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com # 실제 이메일 주소로 변경해주세요
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
            - kind: Gateway # 또는 HTTPRoute (어떤 Gateway API 리소스를 참조하는지에 따라 다름)
              name: jenkins-gateway # 참조할 Gateway 또는 HTTPRoute의 이름
              namespace: jenkins # 참조할 Gateway 또는 HTTPRoute의 네임스페이스
