apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minseoky/gitops.git
    targetRevision: prod
    path: cert-manager
    kustomize:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - Replace=true
      - AddOwnerRef=true
      - PruneLast=true
    retry: # 이 부분을 추가합니다.
      limit: 5 # 최대 재시도 횟수
      backoff:
        duration: 10s # 첫 번째 재시도까지 10초 대기
        factor: 2 # 다음 재시도까지 대기 시간을 두 배로 늘림 (10s, 20s, 40s, ...)
        maxDuration: 2m # 최대 대기 시간
