apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minseoky/gitops.git    # Actual Git URL
    targetRevision: prod
    path: istio-system/istio
    kustomize:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
      - Replace=true
      - AddOwnerRef=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
    jsonPointers:
    - /webhooks/0/failurePolicy
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: istio-validator-istio-system
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
