apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jenkins-gateway
  namespace: jenkins
spec:
  hostnames:
    - jenkins.minseoky.me
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: jenkins-gateway
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: jenkins
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
