apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: jenkins-gateway
  namespace: jenkins
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "jenkins.minseoky.me"
      allowedRoutes:
        namespaces:
          from: Same
